/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BottomMenu: typeof import('./components/BottomMenu.vue')['default']
    ChatInput: typeof import('./components/Chat/ChatInput.vue')['default']
    ChatView: typeof import('./components/Chat/ChatView.vue')['default']
    DashboardWallet: typeof import('./components/Dashboard/DashboardWallet.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    QuickActions: typeof import('./components/Dashboard/QuickActions.vue')['default']
    ReceiverCard: typeof import('./components/Chat/ReceiverCard.vue')['default']
    RecentTransactions: typeof import('./components/Dashboard/RecentTransactions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SenderCard: typeof import('./components/Chat/SenderCard.vue')['default']
  }
}
